import { useEffect, useState } from 'react';
const emptyInfo = { name: '', phone: '', whatsapp: '', email: '', address: '', mapLat: '', mapLng: '', socialLinks: { facebook: '', instagram: '' } };
const ClinicInfoForm = ({ info, isSaving, onSubmit }) => {
  const [form, setForm] = useState(emptyInfo);
  useEffect(() => { setForm(info ? { ...emptyInfo, ...info, mapLat: info.mapLat ?? '', mapLng: info.mapLng ?? '', socialLinks: { ...emptyInfo.socialLinks, ...info.socialLinks } } : emptyInfo); }, [info]);
  const updateField = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value })); const updateSocial = (event) => setForm((current) => ({ ...current, socialLinks: { ...current.socialLinks, [event.target.name]: event.target.value } }));
  const submit = (event) => { event.preventDefault(); onSubmit({ ...form, mapLat: form.mapLat === '' ? undefined : Number(form.mapLat), mapLng: form.mapLng === '' ? undefined : Number(form.mapLng) }); };
  return <form onSubmit={submit} className="max-w-3xl rounded-2xl border border-[#E0F2F1] bg-white p-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-gray-700">اسم العيادة<input name="name" value={form.name} onChange={updateField} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label><label className="text-sm font-medium text-gray-700">البريد الإلكتروني<input name="email" type="email" value={form.email} onChange={updateField} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label><label className="text-sm font-medium text-gray-700">الهاتف<input name="phone" value={form.phone} onChange={updateField} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label><label className="text-sm font-medium text-gray-700">واتساب<input name="whatsapp" value={form.whatsapp} onChange={updateField} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label><label className="text-sm font-medium text-gray-700 sm:col-span-2">العنوان<textarea name="address" rows="2" value={form.address} onChange={updateField} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label><label className="text-sm font-medium text-gray-700">Facebook<input name="facebook" value={form.socialLinks.facebook} onChange={updateSocial} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label><label className="text-sm font-medium text-gray-700">Instagram<input name="instagram" value={form.socialLinks.instagram} onChange={updateSocial} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label><label className="text-sm font-medium text-gray-700">خط العرض<input name="mapLat" type="number" step="any" value={form.mapLat} onChange={updateField} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label><label className="text-sm font-medium text-gray-700">خط الطول<input name="mapLng" type="number" step="any" value={form.mapLng} onChange={updateField} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2" /></label></div><button type="submit" disabled={isSaving} className="mt-6 rounded-lg bg-[#0F766E] px-6 py-2.5 font-medium text-white hover:bg-[#0d6259] disabled:opacity-60">{isSaving ? 'جاري الحفظ...' : 'حفظ المعلومات'}</button></form>;
};
export default ClinicInfoForm;