import { useCallback, useEffect, useState } from 'react';
import { deleteAppointment, getAppointments, updateAppointmentStatus } from '../../api/appointments.api';
import AppointmentsTable from '../../components/admin/AppointmentsTable';

const AdminAppointmentsPage = () => {
  const [appointments, setAppointments] = useState([]); const [filters, setFilters] = useState({ status: '', date: '' }); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const loadAppointments = useCallback(async () => { setIsLoading(true); setError(''); try { const response = await getAppointments(Object.fromEntries(Object.entries(filters).filter(([, value]) => value))); setAppointments(response.data); } catch { setError('تعذر تحميل الحجوزات، حاول تحديث الصفحة'); } finally { setIsLoading(false); } }, [filters]);
  useEffect(() => { loadAppointments(); }, [loadAppointments]);
  const changeFilter = (event) => setFilters((current) => ({ ...current, [event.target.name]: event.target.value }));
  const handleStatusChange = async (id, status) => { try { await updateAppointmentStatus(id, status); setNotice('تم تحديث حالة الحجز'); await loadAppointments(); } catch (err) { setError(err.response?.data?.message || 'تعذر تحديث حالة الحجز'); } };
  const handleDelete = async (appointment) => { if (!window.confirm(`هل تريد حذف حجز ${appointment.patientName}؟`)) return; try { await deleteAppointment(appointment._id); setNotice('تم حذف الحجز'); await loadAppointments(); } catch (err) { setError(err.response?.data?.message || 'تعذر حذف الحجز'); } };
  return <div><div className="mb-6"><h1 className="text-2xl font-bold text-gray-800">الحجوزات</h1><p className="mt-1 text-sm text-gray-500">متابعة مواعيد المرضى وتحديث حالتها.</p></div><div className="mb-5 flex flex-wrap items-end gap-3 rounded-2xl border border-[#E0F2F1] bg-white p-4"><label className="text-sm text-gray-700">التاريخ<input type="date" name="date" value={filters.date} onChange={changeFilter} className="mt-1 block rounded-lg border border-gray-300 px-3 py-2" /></label><label className="text-sm text-gray-700">الحالة<select name="status" value={filters.status} onChange={changeFilter} className="mt-1 block rounded-lg border border-gray-300 px-3 py-2"><option value="">كل الحالات</option><option value="pending">قيد الانتظار</option><option value="confirmed">مؤكد</option><option value="completed">مكتمل</option><option value="cancelled">ملغى</option></select></label><button onClick={() => setFilters({ status: '', date: '' })} className="rounded-lg border border-gray-300 px-4 py-2 text-sm text-gray-700 hover:bg-gray-50">مسح الفلاتر</button></div>{error && <p className="mb-4 rounded-lg border border-red-100 bg-red-50 px-3 py-2 text-sm text-red-600">{error}</p>}{notice && <p className="mb-4 rounded-lg border border-emerald-100 bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{notice}</p>}{isLoading ? <p className="text-gray-500">جاري تحميل الحجوزات...</p> : <AppointmentsTable appointments={appointments} onStatusChange={handleStatusChange} onDelete={handleDelete} />}</div>;
};
export default AdminAppointmentsPage;